language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

mysql:
  database: lento
  username: root
  encoding: utf8
  
before_install:
  - sudo apt-get update > /dev/null
  - mysql -u root -e "CREATE DATABASE lento COLLATE 'utf8_general_ci';" 
  - mysql -u root lento < lento.sql
  - composer install
  
script: phpunit